# Generated by Django 6.0.1 on 2026-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='customers', to='shop.product', verbose_name='Кошик'),
        ),
    ]
